language: python
cache:
  pip: true
  directories:
  - ".cache/result"
  - ".cache/toolchain"
python:
- '2.7'
- '3.6'
- '3.5'
- '3.4'
- pypy

sudo: required
dist: trusty

install:
- pip install tox

script:
- tox # bash .ci/script.sh

deploy:
  provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWD"
  skip_cleanup: true

  on:
    tags: true
    repo: "$TRAVIS_REPO_SLUG"
    python: 3.6
